### ISSUE TITLE
Use `wget` on Ubuntu/Debian

### ISSUE THREAD

**Issue by penberg** [scylladb/scylladb-web-install#15]
`curl` is not installed by default on Ubuntu/Debian so adjust the script to use `wget`.

**Comment by yaronkaikov** [comment]
@Annamikhlin Please see if this is something we wish to implement

**Comment by roydahan** [comment]
I wouldn't waste time on it.

**Comment by tzach** [comment]
Look like `wget` is already used 
https://opensource.docs.scylladb.com/stable/getting-started/install-scylla/install-on-linux.html#install-scylladb
https://www.scylladb.com/download/?platform=ubuntu-22.04&version=scylla-5.4#open-source

**Comment by Annamikhlin** [comment]
since in our internal test flow (git Actions) https://github.com/scylladb/scylladb-web-install/blob/main/.github/workflows/test.yml - we use containers that are not includes `wget` package, we need to take that into account as well.

I'm closing this issue for now. Don't think it's worth spending time for changing the current installation process and in addition, changing our tests.
